### ISSUE TITLE
Revisión estructura y paleta de colores Portafolio

### ISSUE THREAD

**Issue by MarciaMillanao** [Dany-Nok/Dany-Nok#1]
Hola Daniela, falta la estructura y la paleta de colores para revisar.

**Comment by Dany-Nok** [comment]
Hola @MarciaMillanao !
En principio tenía 2 paletas de colores, que estaban dentro de una carpeta en `assets` (por eso no estaban a la vista) pero ahora puse la que espero usar -por ahora- en mi portafolio.

Me demoró más el boceteo o sketching (hecho a mano se ve horrible), porque no sabía muy bien cómo hacer algo para que se viera un poco diferente de los portafolios que he visto...pero ya teniendo una idea un poco mejor pensada, echaré mano a lo que recuerdo de diseño gráfico...estaba super estancada de ideas en realidad :(

Espero ir mejorando lo que tengo pensado en la primera maqueta!

**Comment by MarciaMillanao** [comment]
Daniela, revise es boceto enviado, se ve una estructura definida, como recomendación no pondría una foto a la sección de contacto, ya que tienes una en Sobre Mí, en la sección de tu descripción a que te refieres con link?, además debes recordar tener una versión mobile de tu portafolio.

**Comment by Dany-Nok** [comment]
@MarciaMillanao 
Lo de los "links" es lo que coloqué en la parte de hobbies e intereses. La idea que tengo es que esos íconos contengan una descripción en una sola línea y le puse "link" para identificar que al hacerle hover, pase algo (es para que no se me olvidara qué espero hacer con esos íconos).

La imagen de "sobre mí" no es precisamente una foto mía (sería en ese caso solo el contorno), es algo que quiero ver si me resulta y que se vea otra imagen de fondo al hacerle hover a los íconos...por ahora veré si lo logro hacer, sino pondré alguna imagen estática. Por eso había dejado la segunda foto en el footer
